######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 23 20:40:41 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.h configuration.h coordinate.h dialog.h
FORMS += dialog.ui
SOURCES += ball.cpp configuration.cpp coordinate.cpp dialog.cpp main.cpp
