######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 26 13:00:29 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.h configuration.h coordinate.h dialog.h
FORMS += dialog.ui
SOURCES += ball.cpp configuration.cpp coordinate.cpp dialog.cpp main.cpp

OTHER_FILES += \
    config.txt
